import { Word } from '../types';
import rawVocabData from '../year7_vocabulary_with_cn.json';

/**
 * Static cache files (generated by prebuild script)
 * Priority: Static cache > JSON fallback
 */

// 单元 ID 映射
const UNIT_ID_MAP: Record<string, string> = {
  'Starter Chapter': 'starter',
  'Unit1': 'unit1',
  'Unit2': 'unit2',
  'Unit3': 'unit3',
  'Unit4': 'unit4',
  'Unit5': 'unit5',
  'Unit6': 'unit6',
};

// JSON 数据类型
interface JsonWordEntry {
  word: string;
  meaning: string;
}

interface JsonVocabData {
  [key: string]: JsonWordEntry[];
}

/**
 * 从静态缓存文件获取单词数据（预生成，无需 AI 调用）
 * 优先级最高，由 `npm run prebuild` 生成
 */
async function loadStaticCache(unitId: string): Promise<Word[] | null> {
  try {
    const response = await fetch(`/data/cache/${unitId}.json`);
    if (!response.ok) {
      return null;
    }
    const words = await response.json();
    console.log(`[Static Cache] Unit ${unitId} loaded from static file`);
    return words;
  } catch {
    return null;
  }
}

/**
 * 从 JSON 文件获取基础单词数据（fallback）
 */
function getBasicWordsFromJson(unitId: string): Word[] | null {
  try {
    const vocabData = rawVocabData as JsonVocabData;

    const unitName = Object.keys(UNIT_ID_MAP).find(
      key => UNIT_ID_MAP[key] === unitId
    );

    if (!unitName || !vocabData[unitName]) {
      return null;
    }

    const entries = vocabData[unitName];
    return entries.map((entry, index) => ({
      id: `${unitId}-${index}`,
      term: entry.word,
      definition: entry.meaning,
      example: '',
      unit: unitId,
    }));
  } catch (error) {
    console.error('Error loading preloaded words:', error);
    return null;
  }
}

/**
 * 获取指定单元的单词数据
 * 优先级：静态缓存文件 > JSON 基础数据
 */
export const getPreloadedWords = async (unitId: string): Promise<Word[] | null> => {
  // 1. Try static cache first (pre-generated, no AI needed)
  const staticCache = await loadStaticCache(unitId);
  if (staticCache && staticCache.length > 0) {
    return staticCache;
  }

  // 2. Fall back to JSON basic data
  return getBasicWordsFromJson(unitId);
};

/**
 * 同步版本的 getPreloadedWords（仅用于检查，不返回数据）
 */
export const hasPreloadedData = (unitId: string): boolean => {
  const vocabData = rawVocabData as JsonVocabData;
  const unitName = Object.keys(UNIT_ID_MAP).find(
    key => UNIT_ID_MAP[key] === unitId
  );
  return !!(unitName && vocabData[unitName]);
};

/**
 * 获取所有有预存数据的单元 ID
 */
export const getPreloadedUnitIds = (): string[] => {
  return Object.values(UNIT_ID_MAP);
};
